name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspios_lite_arm64:latest
        commands: |
          uname -a
          whoami

          # Install Docker
          curl -sSL https://get.docker.com | sh

          docker ps




