name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: raspi_4_bullseye:20220121
        commands: |
          uname -a
          whoami

          # Install Docker
          apt update
          apt install curl -y
          curl -sSL https://get.docker.com | sh
          systemctl start docker

          docker ps

          # Build AGW docker images
          git clone https://github.com/m-govind/magma.git --depth 1
          cd magma/lte/gateway/docker/
          docker-compose build --build-arg CPU_ARCH=aarch64 --build-arg DEB_PORT=arm64



